theme: jekyll-theme-minimal
# Site settings
title: yiding-he 的博客
SEOTitle: yiding-he 的博客
header-img: 
email: 
description: "yiding-he 的博客"
keyword: 
url: "https://yiding-he.github.io"          # 这个就是填写你的博客地址
baseurl: ""      # 这个我们不用填写
